### ISSUE TITLE
Accessibility issues: Header component

### ISSUE THREAD

**Issue by daemon-node-byte** [ASU/asu-unity-stack#1149]
# Accessibility issues: Header component

Found a bug related to accessibility within the global Header component. 

## Issue caused by the bug

During accessibility compliance scan. A labeled "**A**" issue was found with "**1.3.1 Info and Relationships**"

> **Container element is empty**
> Some roles are designed to contain other roles. This element has this type of role, but it doesn't contain any [required-owned elements](https://www.w3.org/TR/wai-aria-1.1/#mustContain).

---

## Reproducing the bug.

Importing `@asu/component-header` into an application and configuring the property `HeaderProps.navTree` value to be an empty array (`[]`) 

---
## Proposed bug source 

Header generates `<ul>` tag when there are no `<li>` to map as children.  

*file:*[`<rootDir>/packages/component-header/src/components/HeaderMain/NavbarContainer/index.js`](https://github.com/ASU/asu-unity-stack/blob/dev/packages/component-header/src/components/HeaderMain/NavbarContainer/index.js)

```javascript
// lines 41 - 46
        <ul className="nav-list">
          {!!mobileNavTree?.length && isMobile
            ? mobileNavTree?.map((link, i) => renderItem(link, i))
            : navTree?.map((link, i) => renderItem(link, i))}
        </ul>
```
---

## Proposed solution

Conditionally generate the parent element.

```javascript
        {(mobileNavTree?.length > 0 || navTree?.length > 0) && (
          <ul className="nav-list">
            {!!mobileNavTree?.length && isMobile
              ? mobileNavTree?.map((link, i) => renderItem(link, i))
              : navTree?.map((link, i) => renderItem(link, i))}
          </ul>
        )}
```

**Comment by mlsamuelson** [comment]
We'll address this effort via https://asudev.jira.com/browse/UDS-1467 to keep with our team workflow and have visibility on our board. cc @davidornelas11
